CREATE DATABASE IF NOT EXISTS syntechcraft_db;
USE syntechcraft_db;

CREATE TABLE IF NOT EXISTS projects (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  cat VARCHAR(120) NOT NULL,
  `desc` TEXT NOT NULL,
  tags JSON NOT NULL,
  img LONGTEXT NOT NULL,
  link VARCHAR(500) NULL,
  show_on_home TINYINT(1) NOT NULL DEFAULT 0,
  home_selection_order INT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
